<a href="https://colab.research.google.com/github/SuryaSuresh18/course/blob/main/Practical_session_1_27_07_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.size

3

In [8]:
b=np.array([(1,2,3),(4,5,6)],dtype=float)
b


array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
b.size

6

In [12]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [11]:
c.size

12

In [13]:
b.ndim

2

In [14]:
c.ndim

3

In [15]:
#to check shape
b.shape

(2, 3)

In [16]:
c.shape

(2, 2, 3)

In [17]:
#to find the datatype
b.dtype

dtype('float64')

In [18]:
c.dtype

dtype('float64')

Create an array of zero's

In [22]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create an array of ones

In [24]:
print(np.ones((2,3,4),dtype=np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


Create an array of evenly spaced values

d=np.arange(10,25,5)
d

In [26]:
#Step value is by default 1
#narange(start,end,step)
d=np.arange(10,25)
d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
d=np.arange(10,25,2)
d

array([10, 12, 14, 16, 18, 20, 22, 24])

Create an array of evenly spaced values with no of samples that has been passed

In [29]:
#Generate 9 elements between 0 to 2
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0)

In [31]:
#Create an constant array
e=np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

Create a 2 by 2 identity matrix

In [33]:
f=np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [34]:
f=np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create an array with random values

In [35]:
print(np.random.random((2,2)))

[[0.206892   0.24591396]
 [0.41883238 0.39123643]]


In [43]:
print(np.random.random((2,3)))

[[0.74052297 0.87446164 0.41889004]
 [0.70896385 0.23716664 0.93817741]]


Create an empty array

In [55]:
print(np.empty((3,2)))

[[0.84216005 0.93814394]
 [0.38912064 0.36379813]
 [0.93028627 0.93764394]]


In [62]:
print(np.random.random((3,2)))

[[0.09549446 0.38380533]
 [0.01092364 0.69802998]
 [0.35418198 0.94681166]]


In [57]:
print(np.empty((5,3)))

[[6.58338030e-310 4.88171092e-310 0.00000000e+000]
 [0.00000000e+000 6.58327974e-310 1.50008929e+248]
 [4.31174539e-096 9.80058441e+252 1.23971686e+224]
 [1.05191791e-153 9.03292329e+271 9.08366793e+223]
 [1.06244660e-153 3.44981369e+175 6.32404027e-322]]


Generatying random no using rand function

In [61]:
#Grenerates random number between 3 and 2
print(np.random.rand(3,2))

[[0.25905741 0.52601775]
 [0.70734496 0.55818433]
 [0.75948348 0.76835572]]


In [65]:
np.random.rand()

0.04300125235138319

In [66]:
np.random.randint(1,size=(2,4))


array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [67]:
np.random.randint(5,size=(2,4))

array([[3, 1, 3, 1],
       [1, 4, 4, 2]])

Type of data

In [69]:
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [70]:
g.dtype

dtype('<U1')

In [71]:
g.dtype.name

'str32'

In [72]:
f = np.array([[1,2,3],[4,5,6]],dtype = complex)
f


array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [73]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Basic operations

In [74]:
a = np.arange(4)
a


array([0, 1, 2, 3])

In [75]:
a + 4

array([4, 5, 6, 7])

In [77]:
a * 2

array([0, 2, 4, 6])

In [78]:
a ^ 2

array([2, 3, 0, 1])

In [80]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [81]:
a + b

array([ 4,  6,  8, 10])

In [82]:
a - b

array([-4, -4, -4, -4])

In [83]:
a * b

array([ 0,  5, 12, 21])

In [84]:
A = np.arange(0,9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
B = np.ones((3,8))
B


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [86]:
np.dot(A,B)

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [21., 21., 21., 21., 21., 21., 21., 21.]])

In [87]:
A.dot(B)

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [21., 21., 21., 21., 21., 21., 21., 21.]])

In [89]:
A.dot(B)

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [21., 21., 21., 21., 21., 21., 21., 21.]])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a += 1

In [92]:
a


array([1, 2, 3, 4])

In [93]:
a -= 1
a

array([0, 1, 2, 3])

Aggregate functions

In [95]:
a = np.array([3.3,4.5,1.2,5.7,0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [96]:
a.sum()

15.0

In [97]:
a.min()

0.3

In [98]:
a.max()

5.7

In [100]:
a.std()

2.0079840636817816

In [102]:
a = np.arange(10,16)
a


array([10, 11, 12, 13, 14, 15])

In [103]:
a[2]

12

In [104]:
a[-1]
a


array([10, 11, 12, 13, 14, 15])

In [105]:
a[-1]

15

In [108]:
a [1:5:2]

array([11, 13])

In [109]:
a[::2]

array([10, 12, 14])

In [110]:
a[:5:2]

array([10, 12, 14])

In [111]:
a[1:5]

array([11, 12, 13, 14])

In [112]:
A = np.arange(10,19).reshape(3,3)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [113]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])